In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("D:/Akshay/Quant/QuantForge/modules/asset_research/data/raw_data/equity/equity_daily.parquet")

In [3]:
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Symbol
0,1980-12-12 00:00:00-05:00,0.128348,0.128906,0.128348,0.128348,0.098207,469033600,0.0,0.0,AAPL
1,1980-12-15 00:00:00-05:00,0.122210,0.122210,0.121652,0.121652,0.093083,175884800,0.0,0.0,AAPL
2,1980-12-16 00:00:00-05:00,0.113281,0.113281,0.112723,0.112723,0.086251,105728000,0.0,0.0,AAPL
3,1980-12-17 00:00:00-05:00,0.115513,0.116071,0.115513,0.115513,0.088386,86441600,0.0,0.0,AAPL
4,1980-12-18 00:00:00-05:00,0.118862,0.119420,0.118862,0.118862,0.090949,73449600,0.0,0.0,AAPL
5,1980-12-19 00:00:00-05:00,0.126116,0.126674,0.126116,0.126116,0.096499,48630400,0.0,0.0,AAPL
6,1980-12-22 00:00:00-05:00,0.132254,0.132813,0.132254,0.132254,0.101196,37363200,0.0,0.0,AAPL
7,1980-12-23 00:00:00-05:00,0.137835,0.138393,0.137835,0.137835,0.105466,46950400,0.0,0.0,AAPL
8,1980-12-24 00:00:00-05:00,0.145089,0.145647,0.145089,0.145089,0.111017,48003200,0.0,0.0,AAPL
9,1980-12-26 00:00:00-05:00,0.158482,0.159040,0.158482,0.158482,0.121264,55574400,0.0,0.0,AAPL

In [5]:
df.shape

(70280, 10)

################ Different ways to count

In [12]:
df["Symbol"].nunique()

10

In [13]:
df["Symbol"].value_counts()

Symbol
JPM      11669
AAPL     11481
MSFT     10155
AMZN      7329
NVDA      6904
GOOGL     5503
MA        5058
V         4602
TSLA      4028
META      3551
Name: count, dtype: int64

In [14]:
df["Symbol"].value_counts().reset_index()

  Symbol  count
0    JPM  11669
1   AAPL  11481
2   MSFT  10155
3   AMZN   7329
4   NVDA   6904
5  GOOGL   5503
6     MA   5058
7      V   4602
8   TSLA   4028
9   META   3551

In [15]:
df["Symbol"].value_counts().sort_values(ascending=False)

Symbol
JPM      11669
AAPL     11481
MSFT     10155
AMZN      7329
NVDA      6904
GOOGL     5503
MA        5058
V         4602
TSLA      4028
META      3551
Name: count, dtype: int64

In [10]:
df.groupby("Symbol").agg({"Close": "mean", "Volume": "sum"}).reset_index().sort_values(by="Volume", ascending=False)

  Symbol       Close         Volume
7   NVDA   16.900071  3997183617300
0   AAPL   31.585888  3523394509900
1   AMZN   49.203957   966912949300
2  GOOGL   61.951492   605914954056
6   MSFT   76.625742   561675400000
8   TSLA  108.737878   384890415300
3    JPM   55.370176   138312085700
5   META  235.275536    99129211100
9      V  130.603069    63858017000
4     MA  185.836886    51311181800

In [21]:
df.groupby("Symbol")["Date"].agg(["min", "max"]).reset_index().sort_values(by="min", ascending=True)

  Symbol                       min                       max
3    JPM 1980-03-17 00:00:00-05:00 2026-07-06 00:00:00-04:00
0   AAPL 1980-12-12 00:00:00-05:00 2026-07-06 00:00:00-04:00
6   MSFT 1986-03-13 00:00:00-05:00 2026-07-06 00:00:00-04:00
1   AMZN 1997-05-15 00:00:00-04:00 2026-07-06 00:00:00-04:00
7   NVDA 1999-01-22 00:00:00-05:00 2026-07-06 00:00:00-04:00
2  GOOGL 2004-08-19 00:00:00-04:00 2026-07-06 00:00:00-04:00
4     MA 2006-05-25 00:00:00-04:00 2026-07-06 00:00:00-04:00
9      V 2008-03-19 00:00:00-04:00 2026-07-06 00:00:00-04:00
8   TSLA 2010-06-29 00:00:00-04:00 2026-07-06 00:00:00-04:00
5   META 2012-05-18 00:00:00-04:00 2026-07-06 00:00:00-04:00

## Data Cleaning and Validation Checklist

### Step 1: Load the data
- Read the Parquet file into a pandas DataFrame.
- Confirm the file path is correct and the data is loaded successfully.

In [25]:
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,Symbol
0,1980-12-12 00:00:00-05:00,0.128348,0.128906,0.128348,0.128348,0.098207,469033600,0.0,0.0,AAPL
1,1980-12-15 00:00:00-05:00,0.122210,0.122210,0.121652,0.121652,0.093083,175884800,0.0,0.0,AAPL
2,1980-12-16 00:00:00-05:00,0.113281,0.113281,0.112723,0.112723,0.086251,105728000,0.0,0.0,AAPL
3,1980-12-17 00:00:00-05:00,0.115513,0.116071,0.115513,0.115513,0.088386,86441600,0.0,0.0,AAPL
4,1980-12-18 00:00:00-05:00,0.118862,0.119420,0.118862,0.118862,0.090949,73449600,0.0,0.0,AAPL

## Step 2: Inspect the dataset structure
- Check the number of rows and columns.
- View the column names.
- Review the data types of each column.

In [27]:
df.shape

(70280, 10)

In [26]:
df["Symbol"].value_counts().reset_index()

  Symbol  count
0    JPM  11669
1   AAPL  11481
2   MSFT  10155
3   AMZN   7329
4   NVDA   6904
5  GOOGL   5503
6     MA   5058
7      V   4602
8   TSLA   4028
9   META   3551

In [28]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume',
       'Dividends', 'Stock Splits', 'Symbol'],
      dtype='object')

In [29]:
df.dtypes

Date            datetime64[ns, America/New_York]
Open                                     float64
High                                     float64
Low                                      float64
Close                                    float64
Adj Close                                float64
Volume                                     int64
Dividends                                float64
Stock Splits                             float64
Symbol                                    object
dtype: object

### Step 3: Validate the date column
- Ensure the date column is in datetime format.
- Sort the data by symbol and date.
- Check that dates are in a logical order.

In [ ]:
# Ensure Date is datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [ ]:
# check if  it replaces it with NaT (missing date, note-a-date).
df[df["Date"]==pd.NaT] 
#or 
df[df["Date"].isna()]

Empty DataFrame
Columns: [Date, Open, High, Low, Close, Adj Close, Volume, Dividends, Stock Splits, Symbol]
Index: []

In [41]:
df = df.sort_values(by=["Symbol", "Date"]).reset_index(drop=True)
# Check the result
print(df["Date"].head())
print(df["Date"].dtype)

# Check whether any invalid dates were introduced
print("Missing dates:", df["Date"].isna().sum())

0   1980-12-12 00:00:00-05:00
1   1980-12-15 00:00:00-05:00
2   1980-12-16 00:00:00-05:00
3   1980-12-17 00:00:00-05:00
4   1980-12-18 00:00:00-05:00
Name: Date, dtype: datetime64[ns, America/New_York]
datetime64[ns, America/New_York]
Missing dates: 0

In [43]:
#show date range per symbol
df.groupby("Symbol")["Date"].agg(["min", "max"]).reset_index()

  Symbol                       min                       max
0   AAPL 1980-12-12 00:00:00-05:00 2026-07-06 00:00:00-04:00
1   AMZN 1997-05-15 00:00:00-04:00 2026-07-06 00:00:00-04:00
2  GOOGL 2004-08-19 00:00:00-04:00 2026-07-06 00:00:00-04:00
3    JPM 1980-03-17 00:00:00-05:00 2026-07-06 00:00:00-04:00
4     MA 2006-05-25 00:00:00-04:00 2026-07-06 00:00:00-04:00
5   META 2012-05-18 00:00:00-04:00 2026-07-06 00:00:00-04:00
6   MSFT 1986-03-13 00:00:00-05:00 2026-07-06 00:00:00-04:00
7   NVDA 1999-01-22 00:00:00-05:00 2026-07-06 00:00:00-04:00
8   TSLA 2010-06-29 00:00:00-04:00 2026-07-06 00:00:00-04:00
9      V 2008-03-19 00:00:00-04:00 2026-07-06 00:00:00-04:00

In [ ]:
# check whether the dates are strictly increasing per symbol with:
df.groupby("Symbol")["Date"].is_monotonic_increasing

Symbol
AAPL     True
AMZN     True
GOOGL    True
JPM      True
MA       True
META     True
MSFT     True
NVDA     True
TSLA     True
V        True
Name: Date, dtype: bool

### Step 4: Validate identifiers
- Confirm that the Symbol column exists.
- Check for missing, blank, or inconsistent symbol values.

In [ ]:
# Write your code for Step 4 here

### Step 5: Check for duplicates
- Identify duplicate rows.
- Check for duplicates based on Symbol + Date.

In [ ]:
# Write your code for Step 5 here

### Step 6: Check missing values
- Review missing values in important columns such as Date, Open, High, Low, Close, and Volume.
- Decide whether to drop or fill missing values based on the business logic.

In [ ]:
# Write your code for Step 6 here

### Step 7: Validate numeric fields
- Ensure price columns are numeric.
- Ensure volume is non-negative.
- Check for unrealistic values such as negative prices or zero/negative volume where it should not occur.

In [ ]:
# Write your code for Step 7 here

### Step 8: Check time-series consistency
- For each symbol, verify that dates are unique, the series is sorted, and there are no obvious gaps or irregularities unless expected.

In [ ]:
# Write your code for Step 8 here

### Step 9: Create a cleaned dataset
- Keep the raw data unchanged.
- Create a cleaned version for analysis.
- Apply only minimal and justified cleaning rules at this stage.

In [ ]:
# Write your code for Step 9 here

### Step 10: Produce a QC summary
- Report total row count, number of unique symbols, missing values count, duplicate count, and date range per symbol.

In [ ]:
# Write your code for Step 10 here